<?php

declare(strict_types=1);

/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace APIMATICCalculatorLib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): \APIMATICCalculatorLib\APIMATICCalculatorClient
    {
        $clientBuilder = \APIMATICCalculatorLib\APIMATICCalculatorClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \APIMATICCalculatorLib\APIMATICCalculatorClientBuilder $builder
    ): \APIMATICCalculatorLib\APIMATICCalculatorClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \APIMATICCalculatorLib\APIMATICCalculatorClientBuilder $builder
    ): \APIMATICCalculatorLib\APIMATICCalculatorClientBuilder {
        $timeout = getenv('APIMATIC_CALCULATOR_LIB_TIMEOUT');
        $numberOfRetries = getenv('APIMATIC_CALCULATOR_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('APIMATIC_CALCULATOR_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('APIMATIC_CALCULATOR_LIB_ENVIRONMENT');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
